apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarqube25
  name: sonarqube25
  namespace: standard-cicd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sonarqube25
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sonarqube25
        version: v1
      namespace: standard-cicd
    spec:
      containers:
        - env:
            - name: SONAR_JDBC_URL
              value: >-
                jdbc:postgresql://localhost:5432/sonar10?useUnicode=true&characterEncoding=utf-8&useSSL=true&stringtype=unspecified&escapeSyntaxCallMode=callIfNoReturn&options=-c%20timezone%3DAsia/Shanghai
            - name: SONAR_JDBC_USERNAME
              value: jdbc_name
            - name: SONAR_JDBC_PASSWORD
              value: jdbc_pwd
          image: >-
            swr.cn-north-4.myhuaweicloud.com/tyc-base/sonarqube-enterprise:25.4-v1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/system/status
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 6
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: sonarqube25
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /api/system/status
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: '6'
              memory: 8Gi
            requests:
              cpu: '6'
              memory: 8Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
